version: '3.7'
services:
  jira:
    image: wangcl/atlassian-jira:8.3.1
    restart: always
    build:
      context: jira
    links:
      - database
    volumes:
      - jira-data:/var/atlassian/jira
    environment:
    - CATALINA_OPTS='-Xmx8G'
    networks:
      atlassian_network:
        ipv4_address: 172.18.0.4

  confluence:
    image: wangcl/atlassian-confluence:7.9.3
    restart: always
    build:
      context: confluence
    ports:
      - "8090:8090"
    links:
      - database
    volumes:
      - confluence-data:/var/atlassian/confluence
    networks:
      atlassian_network:
        ipv4_address: 172.18.0.2
  
  bamboo:
    image: wangcl/atlassian-bamboo:6.8.0
    restart: always
    build:
      context: bamboo
    ports:
      - "8085:8085"
    links:
      - database
    volumes:
      - bamboo-data:/var/atlassian/bamboo
    networks:
      atlassian_network:
        ipv4_address: 172.18.0.7

  bitbucket:
    image: atlassian/bitbucket-server:6.3.1
    restart: always
    build:
      context: bitbucket
    ports:
      - "7999:7999"
      - "7990:7990"
    links:
      - database
    volumes:
      - bitbucket-data:/var/atlassian/application-data/bitbucket
    networks:
      atlassian_network:
        ipv4_address: 172.18.0.3
  desk:
    image: wangcl/atlassian-desk:4.21.0
    restart: always
    build:
      context: desk
    links:
      - database
    volumes:
      - desk-data:/var/atlassian/jira
    networks:
      atlassian_network:
        ipv4_address: 172.18.0.8
        
  database:
    image: postgres:11
    restart: always
    ports:
     - "5432:5432"
    environment:
       POSTGRES_USER: postgres
       POSTGRES_PASSWORD: postgres
    volumes:
      - database-data:/var/lib/postgresql/data
    networks:
      atlassian_network:
        ipv4_address: 172.18.0.5
  nginx:
    image: nginx
    restart: always
    ports:
      - "80:80"
    # links:
    #   - jira
    #   # - confluence
    #   - bitbucket
    volumes:
    - ./:/src
    command: bash /src/scripts/run_nginx.sh
    networks:
      atlassian_network:
        ipv4_address: 172.18.0.6
    environment:
    - DOMAIN=dyrs.online
volumes:
  jira-data:
    driver: local
    driver_opts:
      type: none
      device: /opt/data/jira-data
      o: bind
  confluence-data:
    driver: local
    driver_opts:
      type: none
      device: /opt/data/confluence-data
      o: bind
  bamboo-data:
      driver: local
      driver_opts:
        type: none
        device: /opt/data/bamboo-data
        o: bind
  desk-data:
      driver: local
      driver_opts:
        type: none
        device: /opt/data/desk-data
        o: bind
  bitbucket-data:
    driver: local
    driver_opts:
      type: none
      device: /opt/data/bitbucket-data
      o: bind
  database-data:
    driver: local
    driver_opts:
      type: none
      device: /opt/data/database-data
      o: bind

networks:
  atlassian_network:
    ipam:
      driver: default
      config:
        - subnet: 172.18.0.0/16
        # - gateway: 172.18.0.1